<x-admin-layout :pageTitle="'AI Price Suggestions'" :breadcrumbs="['Admin' => route('admin.dashboard'), 'AI Price Suggestions' => route('admin.price-suggestions.index')]">

    {{-- Page Header --}}
    <div class="mb-6 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
            <h1 class="text-2xl font-bold text-gray-900">AI Price Suggestions</h1>
            <p class="text-sm text-gray-500 mt-1">Review and act on AI-generated price recommendations for your products.</p>
        </div>
        <div class="flex items-center gap-2">
            <span class="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full text-xs font-semibold bg-amber-100 text-amber-800 border border-amber-200">
                <svg class="w-3 h-3" fill="currentColor" viewBox="0 0 24 24"><path d="M12 2L1 21h22L12 2zm0 3.5L20.5 19h-17L12 5.5zM11 10v4h2v-4h-2zm0 6v2h2v-2h-2z"/></svg>
                {{ $suggestions->total() }} pending
            </span>
        </div>
    </div>

    {{-- Session Messages --}}
    @if(session('success'))
        <div class="mb-4 flex items-center gap-3 p-4 bg-green-50 border border-green-200 rounded-lg text-sm text-green-800">
            <svg class="w-5 h-5 text-green-500 flex-shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                <path stroke-linecap="round" stroke-linejoin="round" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
            {{ session('success') }}
        </div>
    @endif

    @if(session('error'))
        <div class="mb-4 flex items-center gap-3 p-4 bg-red-50 border border-red-200 rounded-lg text-sm text-red-800">
            <svg class="w-5 h-5 text-red-500 flex-shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
            </svg>
            {{ session('error') }}
        </div>
    @endif

    {{-- Info Banner --}}
    <div class="mb-6 p-4 bg-indigo-50 border border-indigo-100 rounded-xl flex items-start gap-3">
        <div class="p-2 bg-indigo-100 rounded-lg flex-shrink-0">
            <svg class="w-5 h-5 text-indigo-600" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                <path stroke-linecap="round" stroke-linejoin="round" d="M13 10V3L4 14h7v7l9-11h-7z" />
            </svg>
        </div>
        <div>
            <p class="text-sm font-semibold text-indigo-900">Powered by Electro AI Engine</p>
            <p class="text-xs text-indigo-700 mt-0.5">These suggestions are generated by analyzing product data, stock levels, and market conditions. <strong>Approving</strong> will immediately update the product price.</p>
        </div>
    </div>

    {{-- Suggestions Table --}}
    <div class="bg-white rounded-xl border border-gray-200 shadow-sm overflow-hidden">
        <div class="overflow-x-auto">
            <table class="w-full text-sm text-left">
                <thead class="text-xs text-gray-500 uppercase bg-gray-50/80 border-b border-gray-200">
                    <tr>
                        <th scope="col" class="px-5 py-3.5 font-semibold">Product</th>
                        <th scope="col" class="px-5 py-3.5 font-semibold text-center">Current Price</th>
                        <th scope="col" class="px-5 py-3.5 font-semibold text-center">Suggested Price</th>
                        <th scope="col" class="px-5 py-3.5 font-semibold text-center">Change</th>
                        <th scope="col" class="px-5 py-3.5 font-semibold text-center">AI Confidence</th>
                        <th scope="col" class="px-5 py-3.5 font-semibold">Reason</th>
                        <th scope="col" class="px-5 py-3.5 font-semibold">Submitted</th>
                        <th scope="col" class="px-5 py-3.5 font-semibold text-right">Actions</th>
                    </tr>
                </thead>
                <tbody class="divide-y divide-gray-100">
                    @forelse($suggestions as $suggestion)
                        @php
                            $diff = $suggestion->getPriceDifference();
                            $diffPercent = round($suggestion->getPriceDifferencePercent(), 1);
                            $isIncrease = $diff > 0;
                            $confidence = $suggestion->getConfidencePercentage();
                            $confidenceColor = match(true) {
                                $confidence >= 80 => ['bg' => 'bg-green-100', 'text' => 'text-green-700', 'bar' => 'bg-green-500'],
                                $confidence >= 60 => ['bg' => 'bg-blue-100', 'text' => 'text-blue-700', 'bar' => 'bg-blue-500'],
                                $confidence >= 40 => ['bg' => 'bg-yellow-100', 'text' => 'text-yellow-700', 'bar' => 'bg-yellow-500'],
                                default          => ['bg' => 'bg-red-100', 'text' => 'text-red-700', 'bar' => 'bg-red-400'],
                            };
                        @endphp
                        <tr class="hover:bg-gray-50/50 transition-colors">

                            {{-- Product --}}
                            <td class="px-5 py-4">
                                <div class="flex items-center gap-3">
                                    {{-- Product Thumbnail --}}
                                    @if($suggestion->product && $suggestion->product->images && $suggestion->product->images->first())
                                        <img src="{{ Storage::url($suggestion->product->images->first()->image_path) }}"
                                             alt="{{ $suggestion->product->name }}"
                                             class="h-10 w-10 rounded-lg object-cover border border-gray-200 flex-shrink-0">
                                    @else
                                        <div class="h-10 w-10 rounded-lg bg-gray-100 border border-gray-200 flex items-center justify-center flex-shrink-0">
                                            <svg class="w-5 h-5 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.5">
                                                <path stroke-linecap="round" stroke-linejoin="round" d="M20.25 7.5l-.625 10.632a2.25 2.25 0 01-2.247 2.118H6.622a2.25 2.25 0 01-2.247-2.118L3.75 7.5M10 11.25h4M3.375 7.5h17.25c.621 0 1.125-.504 1.125-1.125v-1.5c0-.621-.504-1.125-1.125-1.125H3.375c-.621 0-1.125.504-1.125 1.125v1.5c0 .621.504 1.125 1.125 1.125z" />
                                            </svg>
                                        </div>
                                    @endif
                                    <div class="min-w-0">
                                        <div class="font-medium text-gray-900 truncate max-w-[180px]">
                                            {{ $suggestion->product?->name ?? 'N/A' }}
                                        </div>
                                        <div class="text-xs text-gray-400 mt-0.5">ID #{{ $suggestion->product_id }}</div>
                                    </div>
                                </div>
                            </td>

                            {{-- Current Price --}}
                            <td class="px-5 py-4 text-center">
                                <span class="font-semibold text-gray-700">
                                    {{ number_format($suggestion->old_price, 0, ',', '.') }}₫
                                </span>
                            </td>

                            {{-- Suggested Price --}}
                            <td class="px-5 py-4 text-center">
                                <span class="font-bold {{ $isIncrease ? 'text-blue-700' : 'text-orange-600' }}">
                                    {{ number_format($suggestion->new_price, 0, ',', '.') }}₫
                                </span>
                            </td>

                            {{-- Change --}}
                            <td class="px-5 py-4 text-center">
                                <span class="inline-flex items-center gap-1 px-2.5 py-1 rounded-full text-xs font-semibold
                                    {{ $isIncrease ? 'bg-blue-50 text-blue-700' : 'bg-orange-50 text-orange-700' }}">
                                    @if($isIncrease)
                                        <svg class="w-3 h-3" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="3"><path stroke-linecap="round" stroke-linejoin="round" d="M4.5 15.75l7.5-7.5 7.5 7.5" /></svg>
                                    @else
                                        <svg class="w-3 h-3" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="3"><path stroke-linecap="round" stroke-linejoin="round" d="M19.5 8.25l-7.5 7.5-7.5-7.5" /></svg>
                                    @endif
                                    {{ $isIncrease ? '+' : '' }}{{ $diffPercent }}%
                                </span>
                            </td>

                            {{-- Confidence --}}
                            <td class="px-5 py-4 text-center">
                                <div class="inline-flex flex-col items-center gap-1 min-w-[80px]">
                                    <span class="text-xs font-bold {{ $confidenceColor['text'] }}">
                                        {{ $confidence }}% — {{ $suggestion->getConfidenceLabel() }}
                                    </span>
                                    <div class="w-full h-1.5 rounded-full bg-gray-200">
                                        <div class="h-1.5 rounded-full {{ $confidenceColor['bar'] }}" style="width: {{ $confidence }}%"></div>
                                    </div>
                                </div>
                            </td>

                            {{-- Reason --}}
                            <td class="px-5 py-4 max-w-[200px]">
                                <p class="text-sm text-gray-600 line-clamp-2" title="{{ $suggestion->reason }}">
                                    {{ $suggestion->reason ?? '—' }}
                                </p>
                            </td>

                            {{-- Submitted At --}}
                            <td class="px-5 py-4 whitespace-nowrap">
                                <div class="text-sm text-gray-700">{{ $suggestion->created_at->format('d M Y') }}</div>
                                <div class="text-xs text-gray-400">{{ $suggestion->created_at->diffForHumans() }}</div>
                            </td>

                            {{-- Actions --}}
                            <td class="px-5 py-4">
                                <div class="flex items-center justify-end gap-2">
                                    {{-- Approve --}}
                                    <form method="POST" action="{{ route('admin.price-suggestions.approve', $suggestion) }}"
                                          onsubmit="return confirm('Approve this price suggestion? The product price will be updated immediately.')">
                                        @csrf
                                        <button type="submit"
                                                class="inline-flex items-center gap-1.5 px-3 py-1.5 bg-green-600 hover:bg-green-700 text-white text-xs font-semibold rounded-lg transition-colors">
                                            <svg class="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2.5">
                                                <path stroke-linecap="round" stroke-linejoin="round" d="M4.5 12.75l6 6 9-13.5" />
                                            </svg>
                                            Approve
                                        </button>
                                    </form>

                                    {{-- Reject --}}
                                    <form method="POST" action="{{ route('admin.price-suggestions.reject', $suggestion) }}"
                                          onsubmit="return confirm('Reject this price suggestion?')">
                                        @csrf
                                        <button type="submit"
                                                class="inline-flex items-center gap-1.5 px-3 py-1.5 bg-white hover:bg-red-50 text-red-600 border border-red-200 hover:border-red-400 text-xs font-semibold rounded-lg transition-colors">
                                            <svg class="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2.5">
                                                <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
                                            </svg>
                                            Reject
                                        </button>
                                    </form>
                                </div>
                            </td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="8" class="px-6 py-16 text-center">
                                <div class="flex flex-col items-center gap-3">
                                    <div class="p-4 bg-green-50 rounded-full">
                                        <svg class="w-10 h-10 text-green-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1">
                                            <path stroke-linecap="round" stroke-linejoin="round" d="M9 12.75L11.25 15 15 9.75M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                                        </svg>
                                    </div>
                                    <div>
                                        <p class="text-sm font-semibold text-gray-700">All caught up!</p>
                                        <p class="text-xs text-gray-400 mt-1">There are no pending price suggestions at the moment.</p>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    @endforelse
                </tbody>
            </table>
        </div>

        {{-- Pagination --}}
        @if($suggestions->hasPages())
            <div class="px-6 py-4 border-t border-gray-100 flex items-center justify-between">
                <p class="text-sm text-gray-500">
                    Showing <span class="font-medium">{{ $suggestions->firstItem() }}</span>
                    to <span class="font-medium">{{ $suggestions->lastItem() }}</span>
                    of <span class="font-bold text-gray-700">{{ $suggestions->total() }}</span> suggestions
                </p>
                <div>
                    {{ $suggestions->links('vendor.pagination.admin') }}
                </div>
            </div>
        @endif
    </div>

</x-admin-layout>
